version: '2.3'

networks:
  monitor-net:
    driver: bridge

volumes:
    prometheus_data: {}

services:
  grafana:
    image: grafana/grafana:8.2.6
    container_name: grafana
    volumes:
      - ./grafana/data/:/var/lib/grafana
    entrypoint: /run.sh
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_HTTP_PORT=19000
    restart: unless-stopped
    expose:
      - 19000
    user: '104'
    network_mode: host

  prometheus:
    image: prom/prometheus:v2.2.0-rc.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=30d'
      - '--web.enable-lifecycle'
      - '--web.listen-address=localhost:19001'
    restart: unless-stopped
    expose:
      - 19001
    network_mode: host

  nodeexporter2:
    image: prom/node-exporter:latest
    container_name: nodeexporter2
    user: root
    privileged: true
    volumes:
      - /:/host:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc|boot)($$|/)'
      - '--web.listen-address=localhost:19002'
    restart: unless-stopped
    expose:
      - 19002
    network_mode: host

